-- V1.x 第二阶段：预约状态机简化 + 结算快照
-- 状态机：WAITING → IN_SERVICE → COMPLETED（异常 WAITING → CANCELLED|NO_SHOW）
-- 用户决策 2026-09-28：取消确认环节，PENDING_CONFIRM/CONFIRMED 退役。
-- SQLite 翻译说明（2026-09-28 存储层迁移）：
--   * MySQL 版的 DROP CHECK/UPDATE/ADD CHECK/MODIFY DEFAULT 均为 MySQL 专用步骤；
--     SQLite 无法增删表级 CHECK，全新库由 005 直接按最终状态机建表（见 005 头注释），
--     故本文件在 SQLite 上为空操作（保留文件编号与历史语义说明）。
--   * 结算快照两列已并入建表：redemption.service_name → 006，card_transaction.card_name → 004。
